out_root: results # <- need change
out: results_gyx_20181017_lst_1_F_NARF_D # <- need change

dataset:
  name: human
  bs: 4 # batchsize
  image_size: 128
  train:
    train: True
    data_root: /home/shenwenhao/NARF/data/results_gyx_20181017_lst_1_F/train/  # <- need change
    n_mesh: 26
    n_rendered_per_mesh: 100
    n_imgs_per_mesh: 100
  val:
    same_dist:
      train: True
      data_root: /home/shenwenhao/NARF/data/results_gyx_20181017_lst_1_F/same_view  # <- need change
      n_mesh: 26
      n_rendered_per_mesh: 20
      n_imgs_per_mesh: 20
    novel_pose:
      train: False
      data_root: /home/shenwenhao/NARF/data/results_gyx_20181017_lst_1_F/same_view  # <- need change
      n_mesh: 22
      n_rendered_per_mesh: 20
      n_imgs_per_mesh: 20
    novel_view:
      train: True
      data_root: /home/shenwenhao/NARF/data/results_gyx_20181017_lst_1_F/novel_view  # <- need change
      n_mesh: 26
      n_rendered_per_mesh: 20
      n_imgs_per_mesh: 20
    novel_pose_novel_view:
      train: False
      data_root: /home/shenwenhao/NARF/data/results_gyx_20181017_lst_1_F/novel_view  # <- need change
      n_mesh: 22
      n_rendered_per_mesh: 20
      n_imgs_per_mesh: 20


generator_params:
  patch_size: 24
  triplane_dim: 32
  z_tri: 512
  z_b: 512         # background z dim
  z_enarf: 256     # 不知道是什么?
  nerf_params:
    use_gan: False
    hidden_size: 256                       # hidden size of NeRF
    Nc: 48                                 # number of points for coarse sampling
    Nf: 64                                 # number of points for fine sampling
    no_world_pose: False
    concat: True
    density_scale: 1
    se3: True
    # concat
    mask_input: True
    mask_bone_length: False
  

loss:
  nerf_loss_type: mse
  color_coef: 1
  mask_coef: 1

# hyper parameters
num_iter: 100000
lr: 0.01
scheduler_gamma: 0.99995

resume: # path to the snapshot if necessary

# For DDP
master_addr: 'localhost'
master_port: '12355'
backend: 'nccl'
